import { PubSub } from 'graphql-subscriptions';

export const pubsub = new PubSub();

export const TOPICS = {
  QUESTION_STARTED: 'QUESTION_STARTED',
  VOTE_COUNTS_UPDATED: 'VOTE_COUNTS_UPDATED',
  COUNTDOWN_UPDATED: 'COUNTDOWN_UPDATED',
  QUESTION_ENDED: 'QUESTION_ENDED',
  SCOREBOARD_UPDATED: 'SCOREBOARD_UPDATED',
  ROUNDS_RESET: 'ROUNDS_RESET',
};
